## Working with Arrays

Create a 3 x 6-dimensional array, containing only float values. 

In [11]:
import numpy as np
a = np.array([[1,2,3,4,5,6],[2,2,3,4,5,6],[3,2,3,4,5,6]])
print(a)

[[1 2 3 4 5 6]
 [2 2 3 4 5 6]
 [3 2 3 4 5 6]]


Check the dimension you have created is correct (use “*.shape*”)

In [6]:
a.shape

(3, 6)

Substitute the 5th element from the 2nd row with 19.75.

In [7]:
a[1,2]

3

Extract the 2nd and the 3rd row of the array you created. 

In [12]:
a[1:3]

array([[2, 2, 3, 4, 5, 6],
       [3, 2, 3, 4, 5, 6]])